version: "3.8"

networks:
  happy-network:
    driver: bridge

services:
  happy-web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    stdin_open: true
    container_name: happy-web
    restart: always
    command: yarn start
    user: happy:happy
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./web:/home/happy/web
      - ./web/node_modules:/home/happy/web/node_modules

  happy-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: happy-api
    restart: always
    command: yarn dev
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./api:/home/happy/api
      - ./api/node_modules:/home/happy/api/node_modules
    networks:
      - happy-network
    links:
      - happy-postgres
    depends_on:
      - happy-postgres

  happy-postgres:
    image: postgres
    container_name: happy-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DATA=/data/postgres
    networks:
      - happy-network
    volumes:
      - ./infra/db/postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
